type Level @entity(immutable: false) {
  id: ID!
  levelId: BigInt!
  name: String!
  size: Int!
  creator: Bytes!
  createdAt: BigInt!
  hintCount: Int!
  completionCount: BigInt!
  txHash: Bytes!

  hints: [Hint!]! @derivedFrom(field: "level")
  solveRecords: [SolveRecord!]! @derivedFrom(field: "level")
}

type Hint @entity(immutable: true) {
  id: ID!
  level: Level!
  x: Int!
  y: Int!
  value: Int!
}

type SolveRecord @entity(immutable: true) {
  id: Bytes!
  level: Level!
  levelId: BigInt!
  solver: Bytes!
  timestamp: BigInt!
  pathLength: BigInt!
  isFirstCompletion: Boolean!
  txHash: Bytes!
}
