type LevelCreated @entity(immutable: true) {
  id: Bytes!
  levelId: BigInt! # uint256
  creator: Bytes! # address
  name: String! # string
  size: Int! # uint8
  hintsCount: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type LevelSolved @entity(immutable: true) {
  id: Bytes!
  levelId: BigInt! # uint256
  solver: Bytes! # address
  pathLength: BigInt! # uint256
  isFirstCompletion: Boolean! # bool
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
